Fix some bugs found by Claude

diff --git a/assignments/justfile b/assignments/justfile
--- a/assignments/justfile
+++ b/assignments/justfile
@@ -1,17 +1,17 @@
 # Copyright 2026 Danielle Hutzley
-# 
+#
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
-# 
+#
 #   http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-# 
+#
 BUILDDIR := env("BUILDDIR", 'build')
 
 [arg('mode', help="The optimization mode to use")]
@@ -22,33 +22,36 @@ configure mode='debug':
 		"thread-debug") export FLAGS="-Db_sanitize=thread,undefined --optimization=1 -Dcpp_args=-fno-sanitize-recover=undefined";; \
 		"release") export FLAGS="--buildtype=release";; \
 	esac && \
-	meson setup '{{BUILDDIR}}' --reconfigure ${FLAGS}
+	meson setup '{{BUILDDIR}}-{{mode}}' --wipe ${FLAGS}
 
 [arg('mode', help="The optimization mode to use")]
 build mode='debug': (configure mode)
-	ninja -C '{{BUILDDIR}}'
+	ninja -C '{{BUILDDIR}}-{{mode}}'
 
-test: (build "debug")
-    meson test -C "{{BUILDDIR}}"
+test mode='debug': (build mode)
+	meson test -C "{{BUILDDIR}}-{{mode}}"
 
 [arg('executable', help="The executable to run")]
 [arg('mode', help="The optimization mode to use")]
 run executable mode='debug': (build mode)
 	export EXE="$(echo "{{executable}}" | sed -E 's|([^-]*).*|\1/\0|')" && \
-	"{{BUILDDIR}}/${EXE}"
+	"{{BUILDDIR}}-{{mode}}/${EXE}"
 
 [arg('executable', help="The executable to debug")]
 [arg('mode', help="The optimization mode to use")]
 debug executable mode='debug': (build mode)
-	[[ "{{mode}}" == "release" ]] && echo >&2 "Cannot debug a release build" && exit 1
+	if [ "{{mode}}" == "release" ]; then; \
+		echo >&2 "Cannot debug a release build"; \
+		exit 1; \
+	fi
 	export EXE="$(echo "{{executable}}" | sed -E 's|([^-]*).*|\1/\0|')" && \
-	lldb "{{BUILDDIR}}/${EXE}"
+	lldb "{{BUILDDIR}}-{{mode}}/${EXE}"
 
 
 [arg('mode', help="The optimization mode to use")]
 install mode='release': (build mode)
-	meson install -C "{{BUILDDIR}}"
+	meson install -C "{{BUILDDIR}}-{{mode}}"
 
 clean:
-	rm -r '{{BUILDDIR}}'
+	rm -r '{{BUILDDIR}}'*
 
diff --git a/projects/justfile b/projects/justfile
--- a/projects/justfile
+++ b/projects/justfile
@@ -23,36 +23,39 @@ configure project mode='debug':
 		"release") export FLAGS="--buildtype=release";; \
 	esac && \
 	direnv exec '{{project}}' \
-		meson setup '{{project}}/build' '{{project}}' ${FLAGS}
+		meson setup '{{project}}/build-{{mode}}' '{{project}}' ${FLAGS} --wipe
 
 [arg('project', help="Which project to build")]
 [arg('mode', help="The optimization mode to use")]
 build project mode='debug': (configure project mode)
 	direnv exec '{{project}}' \
-		ninja -C '{{project}}/build'
+		ninja -C '{{project}}/build-{{mode}}'
 
-test: (build "debug")
-    meson test -C "{{BUILDDIR}}"
+test project mode='debug': (build project mode)
+    meson test -C "{{project}}/build-{{mode}}"
 
 [arg('project', help="Which project to run")]
 [arg('mode', help="The optimization mode to use")]
 run project mode='debug': (build project mode)
 	direnv exec '{{project}}' \
-		'{{project}}/build/{{project}}'
+		'{{project}}/build-{{mode}}/{{project}}'
 
 [arg('project', help="Which project to debug")]
 [arg('mode', help="The optimization mode to use")]
 debug project mode='debug': (build project mode)
-	[[ "{{mode}}" == "release" ]] && echo >&2 "Cannot debug a release build" && exit 1
+	if [ "{{mode}}" == "release" ]; then; \
+		echo >&2 "Cannot debug a release build"; \
+		exit 1; \
+	fi
 	direnv exec '{{project}}' \
-		lldb '{{project}}/build/{{project}}'
+		lldb '{{project}}/build-{{mode}}/{{project}}'
 
 [arg('project', help="Which project to install")]
 [arg('mode', help="The optimization mode to use")]
 install project mode='release': (build project mode)
 	direnv exec '{{project}}' \
-		meson install -C '{{project}}/build'
+		meson install -C '{{project}}/build-{{mode}}'
 
 [arg('project', help="Which project to clean")]
 clean project:
-	rm -r '{{project}}/build'
+	rm -r '{{project}}/build'*
